from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('employees', '0001_initial'),
        ('authentication', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=20)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
                ('days_allowed_per_year', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('max_carry_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('min_balance_for_encashment', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_paid', models.BooleanField(default=True)),
                ('is_encashable', models.BooleanField(default=False)),
                ('is_carry_forwardable', models.BooleanField(default=False)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('min_days', models.DecimalField(decimal_places=1, default=0.5, max_digits=4)),
                ('max_days', models.DecimalField(decimal_places=1, default=30, max_digits=4)),
                ('advance_days_required', models.PositiveIntegerField(default=0)),
                ('requires_document', models.BooleanField(default=False)),
                ('accrual_type', models.CharField(default='yearly', max_length=15)),
                ('gender_specific', models.CharField(blank=True, max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={'db_table': 'hr_leave_types', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('accrued', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('availed', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('lapsed', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('encashed', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='leave_balances', to='employees.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='balances', to='leave_management.leavetype')),
            ],
            options={'db_table': 'hr_leave_balances',
                     'unique_together': {('employee', 'leave_type', 'year')}},
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_day_type', models.CharField(default='full_day', max_length=15)),
                ('to_day_type', models.CharField(default='full_day', max_length=15)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='leave/documents/')),
                ('status', models.CharField(default='pending', max_length=15)),
                ('manager_status', models.CharField(blank=True, max_length=15)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_status', models.CharField(blank=True, max_length=15)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='leave_applications', to='employees.employee')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='hr_leave_reviews', to='authentication.user')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    to='leave_management.leavetype')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='manager_leave_reviews', to='authentication.user')),
            ],
            options={'db_table': 'hr_leave_applications', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(max_length=15)),
                ('year', models.PositiveIntegerField()),
                ('is_optional', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='employees.location')),
            ],
            options={'db_table': 'hr_holiday_calendar', 'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='LeaveCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='cancellations', to='leave_management.leaveapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
            options={'db_table': 'hr_leave_cancellations'},
        ),
    ]
