from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('employees', '0001_initial'),
        ('shifts', '0001_initial'),
        ('authentication', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[
                    ('present','Present'),('absent','Absent'),('half_day','Half Day'),
                    ('late_mark','Late Mark'),('holiday','Holiday'),('week_off','Week Off'),
                    ('on_duty','On Duty'),('work_from_home','Work From Home'),
                    ('leave','Leave'),('comp_off','Comp Off'),('short_leave','Short Leave'),
                ], default='absent', max_length=20)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('break_in', models.DateTimeField(blank=True, null=True)),
                ('break_out', models.DateTimeField(blank=True, null=True)),
                ('total_break_minutes', models.PositiveIntegerField(default=0)),
                ('total_working_minutes', models.PositiveIntegerField(default=0)),
                ('effective_working_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('early_leaving_minutes', models.PositiveIntegerField(default=0)),
                ('clock_in_source', models.CharField(blank=True, max_length=15)),
                ('clock_out_source', models.CharField(blank=True, max_length=15)),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_in_address', models.TextField(blank=True)),
                ('clock_in_within_geofence', models.BooleanField(blank=True, null=True)),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('clock_out_address', models.TextField(blank=True)),
                ('clock_out_within_geofence', models.BooleanField(blank=True, null=True)),
                ('clock_in_selfie', models.ImageField(blank=True, null=True, upload_to='attendance/selfies/')),
                ('clock_out_selfie', models.ImageField(blank=True, null=True, upload_to='attendance/selfies/')),
                ('is_wfh', models.BooleanField(default=False)),
                ('wfh_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('is_regularized', models.BooleanField(default=False)),
                ('regularized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendance_records', to='employees.employee')),
                ('regularized_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='regularized_attendance', to='authentication.user')),
                ('shift', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift')),
            ],
            options={'db_table': 'hr_attendance', 'ordering': ['-date'],
                     'unique_together': {('employee', 'date')}},
        ),
        migrations.CreateModel(
            name='AttendanceRegularization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('requested_clock_in', models.DateTimeField(blank=True, null=True)),
                ('requested_clock_out', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='regularizations', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='regularizations', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
            options={'db_table': 'hr_attendance_regularization', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ODApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('od_type', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('total_days', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('manager_approved', models.BooleanField(blank=True, null=True)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_approved', models.BooleanField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='od_applications', to='employees.employee')),
                ('hr_approved_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='od_hr_approvals', to='authentication.user')),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='od_manager_approvals', to='authentication.user')),
            ],
            options={'db_table': 'hr_od_applications', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ShortTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='short_time_offs', to='employees.employee')),
            ],
            options={'db_table': 'hr_short_time_off', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SwipeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('swipe_time', models.DateTimeField()),
                ('swipe_type', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=15)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='swipe_logs', to='employees.employee')),
            ],
            options={'db_table': 'hr_swipe_logs', 'ordering': ['-swipe_time']},
        ),
    ]
