from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('employees', '0001_initial'),
        ('authentication', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'hr_salary_structures'},
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('component_type', models.CharField(max_length=10)),
                ('calculation_type', models.CharField(default='fixed', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('formula', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_statutory', models.BooleanField(default=False)),
                ('is_pf_applicable', models.BooleanField(default=False)),
                ('is_esi_applicable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'db_table': 'hr_salary_components'},
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('salary_type', models.CharField(default='monthly', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='salary_records', to='employees.employee')),
                ('revised_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    to='payroll.salarystructure')),
            ],
            options={'db_table': 'hr_employee_salaries', 'ordering': ['-effective_from']},
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=15)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='approved_payrolls', to='authentication.user')),
                ('processed_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='processed_payrolls', to='authentication.user')),
            ],
            options={'db_table': 'hr_payroll_periods',
                     'ordering': ['-year', '-month'],
                     'unique_together': {('month', 'year')}},
        ),
        migrations.CreateModel(
            name='PayslipRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('payslip_number', models.CharField(max_length=30, unique=True)),
                ('total_working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('days_absent', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('days_on_leave', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('days_lop', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('basic', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lwf_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lwf_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lop_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payslip_pdf', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('is_email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=15)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='payslips', to='employees.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='payslips', to='payroll.payrollperiod')),
            ],
            options={'db_table': 'hr_payslips', 'ordering': ['-created_at'],
                     'unique_together': {('payroll_period', 'employee')}},
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('loan_type', models.CharField(max_length=15)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursed_date', models.DateField(blank=True, null=True)),
                ('start_deduction_month', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='loans', to='employees.employee')),
            ],
            options={'db_table': 'hr_loans'},
        ),
    ]
