from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('geo_fence_radius', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'db_table': 'hr_locations'},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sub_departments', to='employees.department')),
            ],
            options={'db_table': 'hr_departments', 'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='designations', to='employees.department')),
            ],
            options={'db_table': 'hr_designations', 'ordering': ['department', 'level']},
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('personal_email', models.EmailField(blank=True)),
                ('official_email', models.EmailField(unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[
                    ('M','Male'),('F','Female'),('O','Other'),('P','Prefer not to say')
                ], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=3)),
                ('marital_status', models.CharField(blank=True, max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('joining_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[
                    ('permanent','Permanent'),('contract','Contract'),
                    ('intern','Intern'),('consultant','Consultant'),('probation','Probation'),
                ], default='permanent', max_length=15)),
                ('status', models.CharField(choices=[
                    ('active','Active'),('inactive','Inactive'),('on_leave','On Leave'),
                    ('resigned','Resigned'),('terminated','Terminated'),('absconding','Absconding'),
                ], default='active', max_length=15)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('separation_reason', models.TextField(blank=True)),
                ('separation_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_employees', to='authentication.user')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name='employees', to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name='employees', to='employees.designation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                    related_name='employees', to='employees.location')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='direct_reports', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='employee_profile', to='authentication.user')),
            ],
            options={'db_table': 'hr_employees', 'ordering': ['first_name', 'last_name']},
        ),
        # CostCenter AFTER Employee so it can FK to Department (already created above)
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                # department FK - matches the actual model
                ('department', models.ForeignKey(blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='employees.department')),
            ],
            options={'db_table': 'hr_cost_centers'},
        ),
        # Now add Employee.cost_center FK (after CostCenter exists)
        migrations.AddField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL, to='employees.costcenter'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='headed_department', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='emergency_contacts', to='employees.employee')),
            ],
            options={'db_table': 'hr_emergency_contacts'},
        ),
        migrations.CreateModel(
            name='EmployeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=30)),
                ('account_type', models.CharField(default='savings', max_length=10)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='bank_accounts', to='employees.employee')),
            ],
            options={'db_table': 'hr_employee_banks'},
        ),
        migrations.CreateModel(
            name='EmployeeStatutory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('uan_number', models.CharField(blank=True, max_length=12)),
                ('pf_number', models.CharField(blank=True, max_length=22)),
                ('esi_number', models.CharField(blank=True, max_length=17)),
                ('pt_number', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('driving_license_number', models.CharField(blank=True, max_length=20)),
                ('driving_license_expiry', models.DateField(blank=True, null=True)),
                ('is_pf_applicable', models.BooleanField(default=True)),
                ('is_esi_applicable', models.BooleanField(default=True)),
                ('is_pt_applicable', models.BooleanField(default=True)),
                ('pf_contribution_type', models.CharField(default='statutory', max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                    related_name='statutory', to='employees.employee')),
            ],
            options={'db_table': 'hr_employee_statutory'},
        ),
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_nominee', models.BooleanField(default=False)),
                ('nominee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_dependent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='family_members', to='employees.employee')),
            ],
            options={'db_table': 'hr_employee_family'},
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('degree', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=300)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('is_highest', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='education', to='employees.employee')),
            ],
            options={'db_table': 'hr_employee_education'},
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True)),
                ('skill_name', models.CharField(max_length=200)),
                ('proficiency', models.CharField(max_length=15)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                    related_name='skills', to='employees.employee')),
            ],
            options={'db_table': 'hr_employee_skills'},
        ),
    ]
